name: Minimum Supported Rust Version

on:
  push:
    branches:
      - main
      - 'run-ci/**'
      - '**/run-ci/**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-msrv:
    name: cargo check MSRV

    strategy:
      matrix:
        os:
          - windows-2022
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash  # Use `bash` even in the Windows job.

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Read the MSRV
        run: |
          msrv="$(just msrv)"
          tee -a "$GITHUB_ENV" <<<"MSRV=$msrv"
      - name: Set up MSRV and nightly toolchains
        run: |
          rustup toolchain install "$MSRV" nightly --profile minimal --no-self-update
      - name: Downgrade locked dependencies to lowest allowed versions
        run: |
          # TODO(msrv): Use `cargo update --minimal-versions` when `--minimal-versions` is available.
          cargo +nightly update -Zminimal-versions
      - name: Run some `cargo build` commands on `gix`
        run: just check-rust-version "$MSRV"

  check-msrv-badge:
    name: Check MSRV badge

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - name: Ensure we start out clean
        run: git diff --exit-code
      - name: Regenerate the MSRV badge
        run: just msrv-badge
      - name: Check for changes
        run: git diff --exit-code

  # Dummy job to have a stable name for the requirement that all MSRV checks pass.
  msrv-pass:
    name: MSRV checks pass

    needs: [ check-msrv, check-msrv-badge ]

    if: always()  # Always run even if dependencies fail.

    runs-on: ubuntu-latest

    steps:
      - name: Fail if ANY dependency has failed or cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
      - name: OK
        run: exit 0
